kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: byoip-mutator-deployment-crb
  labels:
    app: byoip-mutator
subjects:
- kind: ServiceAccount
  name: byoip-mutator-deployment-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: byoip-mutator-deployment-cr
