apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-example
  labels:
    app: admission-webhook-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook-example
  template:
    metadata:
      labels:
        app: admission-webhook-example
      annotations:
        iam.amazonaws.com/role: modify-alb-auth-role
    spec:
      containers:
        - name: admission-webhook-example
          image: 554773729771.dkr.ecr.us-east-1.amazonaws.com/admission-webhook-example:latest
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          env:
            - name: AWS_REGION
              value: us-east-1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-example-certs
