apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  annotations:
    app.brivo.com/ip: 52.54.99.179
  labels:
    app.brivo.com/ip: 52.54.99.179
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
      annotations:
        app.brivo.com/ip: 52.54.99.179
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
