apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  annotations:
    ip.brivo.com/address: "64.35.172.6,64.35.172.7"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sleep
  name: sleep
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sleep
  type: LoadBalancer
