apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "byoip-mutator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "byoip-mutator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: mutating-webhook
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "byoip-mutator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "byoip-mutator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        ip.brivo.com/mutate: skip
        {{- if .Values.labels }}
          {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/apiservice-webhook.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        iam.amazonaws.com/role: {{ .Values.podIAMRole }}
    spec:
      containers:
        - name: byoip-mutator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/tls.crt
            - -tlsKeyFile=/etc/webhook/certs/tls.key
            - -alsologtostderr
            - -v=4
            - 2>&1
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: ENV
              value: {{ .Values.env }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            defaultMode: 420
            secretName: {{ include "byoip-mutator.servingCertificate" . }}
