apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "byoip-mutator.fullname" . }}-cr
  labels:
    app: {{ template "byoip-mutator.fullname" . }}
rules:
- apiGroups:
  - brivo.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "byoip-mutator.fullname" . }}-deployment-crb
  labels:
    app: {{ template "byoip-mutator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "byoip-mutator.fullname" . }}-deployment-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "byoip-mutator.fullname" . }}-deployment-cr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "byoip-mutator.fullname" . }}-deployment-sa
  labels:
    app: {{ template "byoip-mutator.fullname" . }}
