{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "byoip-mutator.serviceAccountName" . }}
  labels:
{{ include "byoip-mutator.labels" . | indent 4 }}
{{- end -}}
